version: '3.7'
services:
  cachewarmer:
    build: .
    image: seosnap_cachewarmer
    container_name: seosnap_cachewarmer
    networks:
      - seosnap_cachewarmer

networks:
  seosnap_cachewarmer:
    driver: bridge
