version: '3.7'
services:
  cachewarmer:
    build:
      context: .
    image: experius/seosnap-cachewarmer:${TAG}
    container_name: seosnap_cachewarmer
    restart: "no"
    environment:
      API_URL:
      API_VER:
      API_NAME:
      API_PASS:
      CACHEWARMER_CACHE_SERVER_URL:
      CACHEWARMER_USER_AGENT:
      CACHEWARMER_THREADS:
      CACHEWARMER_CONCURRENT_REQUESTS:
      CACHEWARMER_LOG_LEVEL:
      CACHEWARMER_BUFFER_SIZE:
    networks:
      - seosnap_cachewarmer

networks:
  seosnap_cachewarmer:
    driver: bridge
